POST http://localhost:3001/api/matches
Content-Type: application/json

{
  "game" : "5e16128e927f3d468440bc6a",
  "players": [
    {
      "player": "5e1761f7d73a6f6253e29a51",
      "points": 10
    }
  ]
}