POST http://localhost:3001/api/matches
Content-Type: application/json

{
  "game" : "5e199e7959f6dc15db820570",
  "players": [
    {
      "player": "5e199e4159f6dc15db82056e",
      "points": 10
    }
  ]
}